on:
  release:
    types: [published]
  workflow_dispatch:

name: Deploy to Amazon S3 / CloudFront

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Build Static Site
      run: dotnet publish -c Release -o ../site-output
      working-directory: BasicTools.Client/
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Sync with S3
      run: aws s3 sync site-output/ s3://basic-tools/

    - name: Invalidate Cloudfront Distribution
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.S3_CLOUDFRONT_DISTRIBUTION }} --paths '/*'