on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Continuous Integration 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test with the dotnet CLI
      run: dotnet test -c Release --no-build