on:
  pull_request:
    types: [opened, edited, reopened]

name: Pull Requests

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test with the dotnet CLI
      run: dotnet test -c Release --no-build